import HeaderMenu from "./components/header_menu";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className="bg-white text-black dark:bg-gray-900 dark:text-white">
        <HeaderMenu />
        {children}
      </body>
    </html>
  );
}
